### PR TITLE
Add conference: React Native EU 2019

### PR DESCRIPTION
**Pull request by jglover**
Added conference: React Native EU 2019. `jglover/conference/elixirconf-2019` should be merged first.

### CODE REVIEW

**Comment by EddyVinck** [comment]
Hi @jglover, could you please also add categories for React Native EU 2019 to your PR?

**Comment by jglover** [comment]
Woops! Thanks for spotting that. Fixing now.

**Comment by jglover** [comment]
This was fixed

**Comment by EddyVinck** [comment]
Looks good, thanks for the fix @jglover !

**Pull request merged**
