### PR TITLE
add JSConf Asia 2019 talks

### PR DESCRIPTION
**Pull request by cecyc**
Addresses part of #15:

* Added all JS Conf Asia 2019 talks, excluding the workshops

### CODE REVIEW

**Comment by EddyVinck** [comment]
Thanks for your contribution @cecyc! In the meantime another PR has been merged. Could you please merge the master branch into your PR and update your IDs?

**Comment by cecyc** [comment]
@EddyVinck Just updated :)

**Comment by EddyVinck** [comment]
@cecyc Sweet, thanks! I'll check it out after dinner

**Comment by EddyVinck** [comment]
@cecyc Thanks for your contribution. Going to merge this in now. I changed a few of the IDs since there were a few minor mistakes, probably made in the process of updating the IDs. We're working on an easier way to contribute data right now, so hopefully this won't be such an inconvenient problem in the future :)

**Comment by cecyc** [comment]
@EddyVinck Thanks so much for fixing that! :)

**Comment by EddyVinck** [comment]
@cecyc no problem! If you'd like make additional contributions and would like an easy way to communicate with other contributors and myself you can join our [community Slack](https://join.slack.com/t/conftalks/shared_invite/enQtNzk1MjA1ODQ2NzM3LTRkMmU0YmRhZDEzYmUxZTEyYjhlMWYzOWIyYTU0NDBkMGFlN2U3MjJmNWE5MjM4ZDM1Yzg0M2QwZWUzODllMzM). We also have a [newsletter](https://emailoctopus.com/lists/b6cc50a1-f282-11e9-be00-06b4694bee2a/forms/subscribe) if you're interested 🙂

**Pull request merged**
