### PR TITLE
Issue #24: Add data for JAMStack Conf SF 2019

### PR DESCRIPTION
**Pull request by jonhenshaw**

### CODE REVIEW

**Comment by EddyVinck** [comment]
Hi @Jon309 I just took a quick look. It seems you made some mistakes with the speaker IDs for the talks. If you check out the preview and compare the speakers in the UI with the speakers in the thumbnail you can see some differences.

**Comment by jonhenshaw** [comment]
> Hi @Jon309 I just took a quick look. It seems you made some mistakes with the speaker IDs for the talks. If you check out the preview and compare the speakers in the UI with the speakers in the thumbnail you can see some differences.

Checking it out now

**Comment by EddyVinck** [comment]
@Jon309 thanks! I also noticed some spelling mistakes for the speaker names. Can you please check those as well?

**Comment by jonhenshaw** [comment]
@EddyVinck I was able to find two typos on speaker names that I just pushed through. I am not currently seeing any issues with the speaker IDs though. I looked at the JSON and went through the YouTube playlist and it looks like all of the speakers match up to the talks unless there's something I'm not seeing. When you mention checking out the "preview" and the "UI", what exactly are you referring to?

**Comment by EddyVinck** [comment]
@Jon309 by preview I meant the preview URL provided by Netlify (see the link at the bottom):
image
https://deploy-preview-26--conftalks.netlify.com/
and by UI I meant the interface of the website

Some names aren't matching with the thumbnails
image
image
image

When you fix this I can merge it in :+1:

**Comment by EddyVinck** [comment]
@Jon309 oh and I just noticed it's "Shawn Erquhart" instead of "Sean Erquhart"

image

**Comment by EddyVinck** [comment]
@Jon309 I fixed a few of the IDs and I'm merging this in now. Thanks a lot for your contribution! If you haven't already joined our [community Slack](https://join.slack.com/t/conftalks/shared_invite/enQtNzk1MjA1ODQ2NzM3LTRkMmU0YmRhZDEzYmUxZTEyYjhlMWYzOWIyYTU0NDBkMGFlN2U3MjJmNWE5MjM4ZDM1Yzg0M2QwZWUzODllMzM), now's the time :wink: We also have a [newsletter :love_letter:](https://emailoctopus.com/lists/b6cc50a1-f282-11e9-be00-06b4694bee2a/forms/subscribe) if you are interested in conferences or ConfTalks and want to stay up to date.

**Pull request merged**
