### PR TITLE
Added ElixirConf 2019

### PR DESCRIPTION
**Pull request by jglover**
Added ElixirConf 2019. Large changeset (56 talks), data pulled from Youtube API and cleaned up manually (removed a few duplicates, fixed missing authors etc).
Due to the size it would be good to merge this quickly to avoid updating many id's

### CODE REVIEW

**Comment by EddyVinck** [comment]
Hi @jglover ! Thanks for your contribution :slightly_smiling_face: 

After fixing this bug https://github.com/EddyVinck/ConfTalks/issues/45 I already promised to merge the [PyCon 2018 PR](https://github.com/EddyVinck/ConfTalks/pull/41) which is also really large (adds over 100 talks). I'll let you know when the bugfix and the PyCon PR have been merged so you can update your IDs. Since this is also a large PR I'm going to prioritize your PR over the smaller ones which are easier to update of course.

**Comment by jglover** [comment]
Thanks Eddy, appreciate it. Fair enough that !41 should get priority since that PR was ready first. Just let me know once it's merged and I'll revise and bump the IDs as appropriate

**Comment by EddyVinck** [comment]
@jglover the PyCon PR has been merged, you can update your IDs now! Please let me know if you have time this week or if I should let someone else update their IDs first

**Comment by EddyVinck** [comment]
@jglover Hi again. Can I let someone else update their IDs first?

**Comment by jglover** [comment]
Hi @EddyVinck, I plan to update the IDs when I wake up in about 4 hours time. If someone can fix theirs and merge it before then go ahead :) 
I've got a couple more branches to open PRs on once all existing ones are merged. I've also been working on a script that will automatically populate the JSON files given a YouTube playlist, more on that when I raise a PR for discussion.

**Comment by jglover** [comment]
Updated @EddyVinck , please review and merge if fit :+1:

**Comment by EddyVinck** [comment]
Thanks @jglover! I'll check it out when I get home :+1:

**Pull request merged**
