### PR TITLE
PyCon 2018, #33

### PR DESCRIPTION
**Pull request by meganvbarton**
added 41 of the talks from PyCon 2018, along with several categories

### CODE REVIEW

**Comment by EddyVinck** [comment]
@meganvbarton is this still a work in progress? Please also make sure you have the latest master branch merged into your fork, see: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork

**Comment by meganvbarton** [comment]
@EddyVinck yes, it is still a work in progress.  That is why it is a draft PR.  There are about 60+ talks from that conference left to add.

**Comment by EddyVinck** [comment]
@meganvbarton no worries! I didn't know this conf has so many videos. I'll postpone other PRs so you can finish this one without having to edit all those IDs afterwards 🙂

**Comment by meganvbarton** [comment]
@EddyVinck this should be all set now!

**Comment by EddyVinck** [comment]
Hi @meganvbarton. Thank you so much for your contribution. 

I took a look at the preview URL: https://deploy-preview-41--conftalks.netlify.com/

And I noticed the displayed speaker not being the speaker of the actual talk for a few of the talks you submitted. I think something might have gone wrong when you fixed your merge conflicts. Some of the videos also aren't working (you can tell by the thumbnail).

Fortunately most of your submitted talks are 100% correct. Some of the talks I noticed that weren't are:
- Get your resources faster, with importlib.resources
- A practical guide to Singular Value Decomposition in Python
- Effortless Logging: A deep dive into the logging module
- Types, Deeper Static Analysis, and you
- Pumping up Python modules using Rust
- The human nature of failure & resiliency
- Reinventing the Parser Generator
- GenZeal: A new generation of thinkers who design, develop, and distribute for tomorrow
- Hard Shouldn't be Hardship: Supporting Absolute Novices to Python

If you could also check the rest to be sure that would be great :slightly_smiling_face: 

Thanks again for your contribution, Megan!

**Comment by meganvbarton** [comment]
@EddyVinck I just made a small change to fix the handful of videos with broken URLs.  

I am not sure what to do about the videos with incorrect authors, as they appear correct in the json files on my branch.  Any thoughts there?

**Comment by EddyVinck** [comment]
@meganvbarton I created an issue to address this problem https://github.com/EddyVinck/ConfTalks/issues/45

I'll take a look at it later today.

**Pull request merged**
